services:
  db-main:
    image: postgres:16
    container_name: blog_db_main
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_MAIN}
    volumes:
      - db_main_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_MAIN}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-users:
    image: postgres:16
    container_name: blog_db_users
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    volumes:
      - db_users_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_USERS}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      db-main:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-main/${POSTGRES_DB_MAIN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    networks:
      - internal

  users_service:
    build: ./users_service
    container_name: users_service
    depends_on:
      db-users:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-users/${POSTGRES_DB_USERS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      BACKEND_SERVICE_URL: ${BACKEND_SERVICE_URL}
    networks:
      - internal

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      push-notificator:
        condition: service_started
      redis:
        condition: service_healthy
      db-users:
        condition: service_healthy
    environment:
      DATABASE_URL_USERS: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-users/${POSTGRES_DB_USERS}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      PUSH_URL: ${PUSH_URL}
    networks:
      - internal

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - users_service
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal


  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    environment:
      URLS: '[{"url": "/api/users/openapi.json", "name": "Users Service"}, {"url": "/api/openapi.json", "name": "Blog Service"}]'
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  push-notificator:
    image: ghcr.io/ayusavin/push-notification-playground:1.0.0
    container_name: push-notificator
    ports:
      - "8001:8000"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_main_data:
  db_users_data:
  redis_data:
