"""error removal from the user table

Revision ID: fa315f19a354
Revises: b551751c3a87
Create Date: 2025-10-12 02:59:51.269977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa315f19a354'
down_revision: Union[str, Sequence[str], None] = 'b551751c3a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # в файле миграции
    op.alter_column('users', 'is_deleted',  # замените на имя вашего столбца
                   existing_type=sa.Boolean(),
                   server_default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
                existing_type=sa.Boolean(),
                server_default=True)
    # ### end Alembic commands ###
