events {
    worker_connections 1024;
}

http {
    upstream backend_upstream {
        server backend:8000;
    }

    upstream users_upstream {
        server users_service:8000;
    }

    upstream swagger_stream {
        server swagger-ui:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/users {
            proxy_pass http://users_upstream/api/users;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api {
            proxy_pass http://backend_upstream/api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /internal {
            proxy_pass http://backend_upstream/internal;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /docs {
            proxy_pass http://swagger_stream/;
        }

        location /swagger-ui-bundle.js {
            proxy_pass http://swagger_stream/swagger-ui-bundle.js;
        }

        location /swagger-ui-standalone-preset.js {
            proxy_pass http://swagger_stream/swagger-ui-standalone-preset.js;
        }

        location /swagger-initializer.js {
            proxy_pass http://swagger_stream/swagger-initializer.js;
        }

        location /index.html {
            proxy_pass http://swagger_stream/index.html;
        }

        location /index.css {
            proxy_pass http://swagger_stream/index.css;
        }

        location /swagger-ui.css {
            proxy_pass http://swagger_stream/swagger-ui.css;
        }

        location /api/users/openapi.json {
            proxy_pass http://users_upstream/openapi.json;
        }

        location /api/openapi.json {
            proxy_pass http://backend_upstream/openapi.json;
        }

        location /health {
            proxy_pass http://backend_upstream/health;
        }
        location /users-health {
            proxy_pass http://users_upstream/health;
        }

        location = / {
            return 301 /docs;
        }
    }
}