"""add foreign keys in subscribers table

Revision ID: 272812a76228
Revises: cd4627cd4513
Create Date: 2026-01-07 15:09:42.951039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272812a76228'
down_revision: Union[str, None] = 'cd4627cd4513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'subscribers', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscribers', 'users', ['subscriber_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    # ### end Alembic commands ###
