"""remove external relationships from user table

Revision ID: 9d0de197ca2d
Revises: ab1fce0b83c4
Create Date: 2025-11-30 20:22:14.577902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0de197ca2d'
down_revision: Union[str, None] = 'ab1fce0b83c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
