"""add_subscriptions_and_keys

Revision ID: cd4627cd4513
Revises: 9d0de197ca2d
Create Date: 2025-12-27 22:57:06.951811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4627cd4513'
down_revision: Union[str, None] = '9d0de197ca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'author_id', name='ux_sub')
    )
    op.create_index(op.f('ix_subscribers_author_id'), 'subscribers', ['author_id'], unique=False)
    op.create_index(op.f('ix_subscribers_subscriber_id'), 'subscribers', ['subscriber_id'], unique=False)
    op.add_column('users', sa.Column('subscription_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_key')
    op.drop_index(op.f('ix_subscribers_subscriber_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_author_id'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
