"""add preview_ur to articles

Revision ID: 2457001731a6
Revises: 26d4d14ebe21
Create Date: 2026-01-08 19:17:19.040114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2457001731a6'
down_revision: Union[str, Sequence[str], None] = '26d4d14ebe21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('preview_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'preview_url')
    # ### end Alembic commands ###
