"""add status to articles

Revision ID: 26d4d14ebe21
Revises: a47d401e9f0b
Create Date: 2026-01-08 17:54:07.987534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d4d14ebe21'
down_revision: Union[str, Sequence[str], None] = 'a47d401e9f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE article_status AS ENUM "
        "('DRAFT', 'PENDING_PUBLISH', 'PUBLISHED', 'REJECTED', 'ERROR')"
    )
    op.add_column('articles', sa.Column('status', sa.Enum('DRAFT', 'PENDING_PUBLISH', 'PUBLISHED', 'REJECTED', 'ERROR', name='article_status'), nullable=False, server_default='DRAFT'))
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_column('articles', 'status')
    op.execute("DROP TYPE article_status")
    # ### end Alembic commands ###
