"""add scopes to api keys table

Revision ID: 4da3e009a45b
Revises: ddabf3f06d39
Create Date: 2026-01-09 03:38:10.704266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da3e009a45b'
down_revision: Union[str, Sequence[str], None] = 'ddabf3f06d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('scopes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'scopes')
    # ### end Alembic commands ###
